# Plan-only tests (no real resources created)
# Tests relating to all the outputs generated by the module

variables {
  team_name = "teamname"
  buckets = [{name = "bucketname", public = false}]
  buckets_to_destroy = []
  allow_destroy = false
}

provider "aws" {
  region = "us-east-2"
}

# Test that the role arn for the generated role is returned for output
run "iam_role_arn_set_for_output" {
  command = plan

  override_resource {
    target = aws_iam_role.team_role
    override_during = plan
    values = {
      arn = "abc123"
    }
  }

  assert {
    condition = aws_iam_role.team_role.arn == output.role_arn
    error_message = "Role ARN is not populated correctly in output"
  }
}

# Tests that full bucket names are returned for the requested buckets, with names formatted correcly
run "bucket_names_set_for_output" {
  command = plan

  variables {
    buckets = [{name = "bucketname1", public = false}, {name = "bucketname2", public = false}]
    team_name = "bm-team"
  }

  override_resource {
    target = aws_s3_bucket.team_bucket["bucketname1"]
    override_during = plan
    values = {
      id = "bmtestcomp--bm-team--bucketname1"
    }
  }

  override_resource {
    target = aws_s3_bucket.team_bucket["bucketname2"]
    override_during = plan
    values = {
      id = "bmtestcomp--bm-team--bucketname2"
    }
  }

  assert {
    condition = length(output.bucket_names) == 2
    error_message = "Output for bucket names does not contain the correct number of elements"
  }

  assert {
    condition = contains(keys(output.bucket_names), var.buckets[0].name)
    error_message = "Output for bucket names does not contain an entry for the first bucket"
  }

  assert {
    condition = contains(keys(output.bucket_names), var.buckets[1].name)
    error_message = "Output for bucket names does not contain an entry for the second bucket"
  }

  assert {
    condition = output.bucket_names[var.buckets[0].name] == "bmsutf--${var.team_name}--${var.buckets[0].name}"
    error_message = "Output for bucket names entry for the first bucket does not match the expected full name"
  }

  assert {
    condition = output.bucket_names[var.buckets[1].name] == "bmsutf--${var.team_name}--${var.buckets[1].name}"
    error_message = "Output for bucket names entry for the second bucket does not match the expected full name"
  }
}